export const GET_DASHBOARD_ANALYTICS = "GET_DASHBOARD_ANALYTICS";
export const GET_DASHBOARD_ANALYTICS_SUCCESS = "GET_DASHBOARD_ANALYTICS_SUCCESS";

export const GET_DASHBOARD_UPDATES = "GET_DASHBOARD_UPDATES";
export const GET_DASHBOARD_UPDATES_SUCCESS = "GET_DASHBOARD_UPDATES_SUCCESS";

export const API_ERROR = "API_ERROR";