export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_SUCCESS ="VERIFY_OTP_SUCCESS";
export const RESEND_OTP_SUCCESS= "RESEND_OTP_SUCCESS";
export const RESEND_OTP = "RESEND_OTP";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const API_ERROR = "LOGIN_API_ERROR";
export const CLEAR_API_ERROR = "CLEAR_API_ERROR";
export const SOCIAL_LOGIN = "SOCIAL_LOGIN";
